### ISSUE TITLE
Logstash stopped processing because of an error: (SystemExit) exit

### ISSUE THREAD

**Issue by davidshanghai** [logstash-plugins/logstash-output-slack#14]
Logstash :  logstash-oss-6.5.1.tar.gz
OS: Red Hat Enterprise Linux Server release 6.9 (Santiago) 
config：     slack {
      url => "xxxxxxxxx"
      channel => "alert"
      username => logstash
      icon_emoji => ":redsiren:"
      attachments => [{text => "%{message}"}]
     format => "OOM occurred on %{host}"
        }

ERROR message ：
      [2019-01-08T07:41:19,207][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<JSON::ParserError: unexpected token at '{"text":"2018-12-17 13:40:29 ERROR [com.common.system.filter.TLThreadContextFilter] -f4363092-936e-4465-80e2-bc2edb9f61df- catching
javax.servlet.ServletException: java.lang.OutOfMemoryError: Java heap space
af.common.system.dao.ldap.ApplicationDaoImpl] -94ef0b94-13e7-417e-9a75-f988923e8e4b- App: 749, urlmapping: , not retrieved from cache"}'>, :backtrace=>["json/ext/Parser.java:250:in `parse'", "/opt/logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/json-1.8.6-java/lib/json/common.rb:155:in `parse'", "/opt/logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-slack-2.1.1/lib/logstash/outputs/slack.rb:64:in `block in receive'", "org/jruby/RubyArray.java:2486:in `map'", "/opt/logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-slack-2.1.1/lib/logstash/outputs/slack.rb:64:in `receive'", "/opt/logstash-6.5.1/logstash-core/lib/logstash/outputs/base.rb:89:in `block in multi_receive'", "org/jruby/RubyArray.java:1734:in `each'", "/opt/ibm/logstash-6.5.1/logstash-core/lib/logstash/outputs/base.rb:89:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:114:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:97:in `multi_receive'", "/opt/logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:373:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/opt/logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:372:in `output_batch'", "/opt/logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:324:in `worker_loop'", "/opt/logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:286:in `block in start_workers'"]}
[2019-01-08T07:41:19,430][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit

Thanks

**Comment by visserp** [comment]
I've got exactly the same sort of error in my project. Could it have to do with tabs or newlines in the log message?

**Comment by simonare** [comment]
Same error here. Is there any solution for this?
